#FROM ubuntu:14.04
FROM pydash:core

#RUN apt-get update && apt-get -y install git python python-pip apache2 libapache2-mod-wsgi


RUN git clone https://github.com/ssgeejr/pydash.git 
#ADD pydash.conf /etc/apache2/sites-enabled/pydash.conf

RUN cd pydash && \
    git checkout develop && \
    python manage.py syncdb --noinput && \
    echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin')" | python manage.py shell

WORKDIR /pydash
EXPOSE :9180
CMD ["python", "manage.py", "runserver","0.0.0.0:9180"]

#CMD service apache2 start;/usr/bin/tail -f /dev/null
