FROM pythonpip

RUN git clone https://github.com/ssgeejr/pydash.git 

RUN cd pydash && \
    git checkout develop && \
    python manage.py syncdb --noinput && \
    echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin')" | python manage.py shell

WORKDIR /pydash
EXPOSE :9180
CMD ["python", "manage.py", "runserver","0.0.0.0:9180"]
